### ISSUE TITLE
Google Calendar integration

### ISSUE THREAD

**Issue by evanpetzoldt** [evanpetzoldt/qsignups-lambda#33]
As the name implies... feel free to add commentary here as you want to @paul-christmann :)

**Comment by paul-christmann** [comment]
What we are building is the ability to publish your events (with or without an assigned Q) to a Google calendar.

1. The ability to connect to your Google Account from the App (via a "Connect") button.  You'll have to authenticate as a user with access to the calendars you want to use.
2. The ability to select a single calendar for all events, or a per-AO calendar.
3. Events will publish to that calendar on a rolling 30 day look ahead (minimizing the look ahead to simplify Google API interactions for managing schedule changes)
4. Updating events to reflect changes in Q schedules

If you're interested in this feature, feel free to upvote, ask questions or comments!
